services:
  transcoder_backend_app:
    build:
      context: ./app  # Path to the app folder where Dockerfile is located
    container_name: transcoder_backend_app
    command: uvicorn app:app --reload --host "0.0.0.0" --port 8000
    ports:
      - 8000:8000  # Bind to all network interfaces
    environment:
      - MONGO_URI=mongodb://root:root@transcoder_backend_db:27017


  transcoder_backend_db:
    image: mongo:5.0
    container_name: transcoder_backend_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
