services:
  transcoder_backend_app:
    build:
      context: ./app  # Path to the app folder where Dockerfile is located
    container_name: transcoder_backend_app
    command: uvicorn app:app --reload --host "0.0.0.0" --port 8000
    ports:
      - 8000:8000  # Bind to all network interfaces
    volumes:
      - ./app:/app  # Bind the app folder to the container
    depends_on:
      - transcoder_backend_db
    env_file:
      - app/.env

  transcoder_backend_db:
    image: postgres:15
    container_name: transcoder_backend_db
    ports:
      - 5432:5432  # Bind to all network interfaces
    environment:
      - POSTGRES_USER=transcoder-dev-db-user
      - POSTGRES_PASSWORD=transcoder-dev-db-password
      - POSTGRES_DB=transcoder-dev-db

