"""video uuid added

Revision ID: 0d3c4fa7dbc3
Revises: 207516733f39
Create Date: 2024-09-28 15:22:13.257335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3c4fa7dbc3'
down_revision: Union[str, None] = '207516733f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_video_uuid'), 'videos', ['video_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_video_uuid'), table_name='videos')
    op.drop_column('videos', 'video_uuid')
    # ### end Alembic commands ###
